source: .
timezone: Asia/Shanghai

markdown: rdiscount
baseurl: /
pygments: true
permalink: /:title
feed: /atom.xml
paginate: 5
paginate_path: "page:num"
title: JackieLin’s blog

url: http://forkme.info

author:
    name: jackieLin
    weibo: http://weibo.com/dashilin
description: 在路上前行的学习者
