source: .
timezone: Asia/Shanghai

markdown: rdiscount
baseurl: /forkme
pygments: true
permalink: /:title
paginate: 5
paginate_path: "page:num"
title: 我就是我，是颜色不一样的烟火
url: http://jackielin.github.io/forkme/

author:
    name: jackieLin
    weibo: http://weibo.com/dashilin
description: 在路上前行的学习者
